id: P002994
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16790
  title: ཁྱུང་གླིང་།
  author: ''
  volumes:
    102c61ad455e46ff802120e2166d9e41:
      image_group_id: I1KG16904
      title: ''
      volume_number: 1
      total_pages: 416
      base_file: v001.txt
